import type { Database } from '@/types/supabase'

// Alias for often types generated by Supabase
export type Candidate = Database['public']['Tables']['candidates']['Row']
export type CandidateInsert = Database['public']['Tables']['candidates']['Insert']
export type CandidateUpdate = Database['public']['Tables']['candidates']['Update']

// Filters for querying candidates
export interface CandidateFilters {
  page?: number
  limit?: number
  search?: string
}

// Interface for candidate list response with data and count
export interface CandidateListResponse {
  data: Candidate[]
  count: number | null
}
