import type { Database } from './supabase'

// Alias for often types generated by Supabase
export type Candidate = Database['public']['Tables']['candidates']['Row']
export type CandidateInsert = Database['public']['Tables']['candidates']['Insert']
export type CandidateUpdate = Database['public']['Tables']['candidates']['Update']
export type JobApplication = Database['public']['Tables']['job_applications']['Row']
export type JobApplicationInsert = Database['public']['Tables']['job_applications']['Insert']
export type JobApplicationUpdate = Database['public']['Tables']['job_applications']['Update']

export type Job = Database['public']['Tables']['jobs']['Row']
export type Interview = Database['public']['Tables']['interviews']['Row']
export type Profile = Database['public']['Tables']['profiles']['Row']
export type Client = Database['public']['Tables']['clients']['Row']
export type Company = Database['public']['Tables']['companies']['Row']
export type CandidateNote = Database['public']['Tables']['candidate_notes']['Row']

export type JobInsert = Database['public']['Tables']['jobs']['Insert']
export type InterviewInsert = Database['public']['Tables']['interviews']['Insert']
export type ProfileInsert = Database['public']['Tables']['profiles']['Insert']
export type ClientInsert = Database['public']['Tables']['clients']['Insert']
export type CompanyInsert = Database['public']['Tables']['companies']['Insert']
export type CandidateNoteInsert = Database['public']['Tables']['candidate_notes']['Insert']

// Types with relations (joined data)
export type CandidateWithApplications = Candidate & {
  applications: JobApplication[]
}
